### ISSUE TITLE
Vercel Build Error SanityPress 5.3.0

### ISSUE THREAD

**Issue by Brettkgamble** [nuotsu/sanitypress#40] opened 2024-12-06 23:33 UTC
SanityPress 5.3.0
- Site runs in Dev

Push to Vercel results in the following error: [see 16:19:21.394]

[16:16:40.819] Running build in Washington, D.C., USA (East) – iad1
[16:16:41.590] Cloning github.com/Brettkgamble/gamble-for-ward-y (Branch: staging, Commit: 56faffc)
[16:16:42.161] Cloning completed: 570.231ms
[16:16:55.850] Restored build cache from previous deployment (H7Dv53Aj8qwyx4FDKoxgavtZxuRP)
[16:16:55.927] Running "vercel build"
[16:16:57.448] Vercel CLI 39.1.3
[16:16:58.680] Installing dependencies...
[16:17:16.397] npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
[16:17:25.456] 
[16:17:25.456] added 61 packages, removed 97 packages, and changed 632 packages in 27s
[16:17:25.456] 
[16:17:25.456] 327 packages are looking for funding
[16:17:25.456]   run `npm fund` for details
[16:17:25.488] Detected Next.js version: 15.0.3
[16:17:25.501] Running "npm run build"
[16:17:25.763] 
[16:17:25.763] > sanitypress@5.3.0 build
[16:17:25.763] > next build
[16:17:25.763] 
[16:17:26.680]    ▲ Next.js 15.0.3
[16:17:26.680] 
[16:17:26.721]    Creating an optimized production build ...
[16:18:58.234]  ✓ Compiled successfully
[16:18:58.240]    Linting and checking validity of types ...
[16:19:00.319] 
[16:19:00.321]  ⚠ The Next.js plugin was not detected in your ESLint configuration. See https://nextjs.org/docs/app/building-your-application/configuring/eslint#migrating-existing-config
[16:19:00.696]  ⨯ ESLint: Error while loading rule '@typescript-eslint/no-empty-function': Cannot read properties of undefined (reading 'allow') Occurred while linting /vercel/path0/src/app/(frontend)/[...slug]/page.tsx
[16:19:08.976]    Collecting page data ...
[16:19:15.168]    Generating static pages (0/21) ...
[16:19:21.393]    Generating static pages (5/21) 
[16:19:21.394] Error occurred prerendering page "/blog". Read more: https://nextjs.org/docs/messages/prerender-error
[16:19:21.394] Error: Unable to parse value of "$limit=undefined". Please quote string values.
[16:19:21.394]     at onResponse (/vercel/path0/.next/server/chunks/5050.js:5:1066)
[16:19:21.399]     at i (/vercel/path0/.next/server/chunks/5050.js:2:2865)
[16:19:21.399]     at /vercel/path0/.next/server/chunks/5050.js:2:3064
[16:19:21.399]     at /vercel/path0/.next/server/chunks/5050.js:2:3173
[16:19:21.399]     at /vercel/path0/.next/server/chunks/5050.js:2:1400
[16:19:21.399]     at u.onreadystatechange (/vercel/path0/.next/server/chunks/5050.js:2:1603)
[16:19:21.399]     at /vercel/path0/.next/server/chunks/5050.js:2:237
[16:19:21.399]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[16:19:21.399] Export encountered an error on /(frontend)/[...slug]/page: /blog, exiting the build.
[16:19:21.400]  ⨯ Static worker exited with code: 1 and signal: null
[16:19:21.465] Error: Command "npm run build" exited with 1
[16:19:22.443]

**Comment by mitchuman** [comment] 2024-12-07 00:44
@Brettkgamble closing as duplicate of #39. A fix is currently on it's way!

Thanks for reporting!

**Closed by mitchuman** 2024-12-07 00:44 UTC
